const dataUser = [
  {
    //  id: 1,
    firstName: "John",
    lastName: "Doe",
    startDate: "04/14/2021",
    department: "Marketing",
    dateOfBirth: "01/01/1990",
    street: "Main Street",
    city: "NY",
    state: "AL",
    zipCode: "01800",
  },
  {
    //  id: 2,
    firstName: "Elisa",
    lastName: "Tyrel",
    startDate: "03/02/2020",
    department: "Marketing",
    dateOfBirth: "01/25/1988",
    street: "Helia Street",
    city: "San Francisco",
    state: "AK",
    zipCode: "85699",
  },
  {
    //  id: 3,
    firstName: "Roland",
    lastName: "Smith",
    startDate: "12/20/2020",
    department: "Sales",
    dateOfBirth: "01/16/1978",
    street: "Cross Street",
    city: "Irvine",
    state: "BK",
    zipCode: "78965",
  },
  {
    // id: 4,
    firstName: "Laetitia",
    lastName: "Menirel",
    startDate: "11/03/2014",
    department: "Engineering",
    dateOfBirth: "08/24/1985",
    street: "High Street",
    city: "Chicago",
    state: "UJ",
    zipCode: "87120",
  },
  {
    //  id: 5,
    firstName: "Kristen",
    lastName: "Bird",
    startDate: "09/20/2012",
    department: "Marketing",
    dateOfBirth: "03/15/1975",
    street: "Side Street",
    city: "Boston",
    state: "VL",
    zipCode: "20369",
  },
  {
    //  id: 6,
    firstName: "Nico",
    lastName: "Smith",
    startDate: "02/02/2017",
    department: "Legal",
    dateOfBirth: "03/29/1987",
    street: "Round Street",
    city: "Detroit",
    state: "DP",
    zipCode: "36124",
  },
  {
    //  id: 7,
    firstName: "Lea",
    lastName: "Regan",
    startDate: "10/08/2015",
    department: "Engineering",
    dateOfBirth: "09/25/1979",
    street: "End Street",
    city: "Baltimore",
    state: "PI",
    zipCode: "79582",
  },
  {
    // id: 8,
    firstName: "Tim",
    lastName: "Legol",
    startDate: "02/13/2021",
    department: "Marketing",
    dateOfBirth: "10/05/1995",
    street: "Holy Street",
    city: "Dallas",
    state: "CM",
    zipCode: "25001",
  },
  {
    // id: 9,
    firstName: "Celia",
    lastName: "Hugh",
    startDate: "04/14/2021",
    department: "Marketing",
    dateOfBirth: "06/14/1992",
    street: "Low Street",
    city: "Austin",
    state: "HY",
    zipCode: "97312",
  },
  {
    // id: 10,
    firstName: "Celia",
    lastName: "Hugh",
    startDate: "04/14/2021",
    department: "Marketing",
    dateOfBirth: "06/14/1992",
    street: "Low Street",
    city: "Austin",
    state: "HY",
    zipCode: "97312",
  },
  {
    // id: 11,
    firstName: "John",
    lastName: "Doe",
    startDate: "04/14/2021",
    department: "Marketing",
    dateOfBirth: "01/01/1990",
    street: "Main Street",
    city: "NY",
    state: "AL",
    zipCode: "01800",
  },
  {
    //  id: 12,
    firstName: "Elisa",
    lastName: "Tyrel",
    startDate: "03/02/2020",
    department: "Marketing",
    dateOfBirth: "01/25/1988",
    street: "Helia Street",
    city: "San Francisco",
    state: "AK",
    zipCode: "85699",
  },
  {
    //  id: 13,
    firstName: "Roland",
    lastName: "Smith",
    startDate: "12/20/2020",
    department: "Sales",
    dateOfBirth: "01/16/1978",
    street: "Cross Street",
    city: "Irvine",
    state: "BK",
    zipCode: "78965",
  },
  {
    // id: 14,
    firstName: "Laetitia",
    lastName: "Menirel",
    startDate: "11/03/2014",
    department: "Engineering",
    dateOfBirth: "08/24/1985",
    street: "High Street",
    city: "Chicago",
    state: "UJ",
    zipCode: "87120",
  },
  {
    //  id: 15,
    firstName: "Roman",
    lastName: "Pelio",
    startDate: "01/28/2018",
    department: "Human Resources",
    dateOfBirth: "05/22/1990",
    street: "Sea Street",
    city: "Seattle",
    state: "SG",
    zipCode: "99852",
  },
  {
    //  id: 16,
    firstName: "Kristen",
    lastName: "Bird",
    startDate: "09/20/2012",
    department: "Marketing",
    dateOfBirth: "03/15/1975",
    street: "Side Street",
    city: "Boston",
    state: "VL",
    zipCode: "20369",
  },
  {
    //  id: 17,
    firstName: "Nico",
    lastName: "Smith",
    startDate: "02/02/2017",
    department: "Legal",
    dateOfBirth: "03/29/1987",
    street: "Round Street",
    city: "Detroit",
    state: "DP",
    zipCode: "36124",
  },
  {
    //  id: 18,
    firstName: "Lea",
    lastName: "Regan",
    startDate: "10/08/2015",
    department: "Engineering",
    dateOfBirth: "09/25/1979",
    street: "End Street",
    city: "Baltimore",
    state: "PI",
    zipCode: "79582",
  },
  {
    // id: 19,
    firstName: "Tim",
    lastName: "Legol",
    startDate: "02/13/2021",
    department: "Marketing",
    dateOfBirth: "10/05/1995",
    street: "Holy Street",
    city: "Dallas",
    state: "CM",
    zipCode: "25001",
  },
  {
    // id: 20,
    firstName: "Celia",
    lastName: "Hugh",
    startDate: "04/14/2021",
    department: "Marketing",
    dateOfBirth: "06/14/1992",
    street: "Low Street",
    city: "Austin",
    state: "HY",
    zipCode: "97312",
  },
  {
    //  id: 21,
    firstName: "John",
    lastName: "Doe",
    startDate: "04/14/2021",
    department: "Marketing",
    dateOfBirth: "01/01/1990",
    street: "Main Street",
    city: "NY",
    state: "AL",
    zipCode: "01800",
  },
  {
    // id: 22,
    firstName: "Elisa",
    lastName: "Tyrel",
    startDate: "03/02/2020",
    department: "Marketing",
    dateOfBirth: "01/25/1988",
    street: "Helia Street",
    city: "San Francisco",
    state: "AK",
    zipCode: "85699",
  },

  {
    // id: 23,
    firstName: "Nico",
    lastName: "Smith",
    startDate: "02/02/2017",
    department: "Legal",
    dateOfBirth: "03/29/1987",
    street: "Round Street",
    city: "Detroit",
    state: "DP",
    zipCode: "36124",
  },
  {
    // id: 24,
    firstName: "Elisa",
    lastName: "Tyrel",
    startDate: "03/02/2020",
    department: "Marketing",
    dateOfBirth: "01/25/1988",
    street: "Helia Street",
    city: "San Francisco",
    state: "AK",
    zipCode: "85699",
  },
  {
    // id: 25,
    firstName: "Roland",
    lastName: "Smith",
    startDate: "12/20/2020",
    department: "Sales",
    dateOfBirth: "01/16/1978",
    street: "Cross Street",
    city: "Irvine",
    state: "BK",
    zipCode: "78965",
  },
  {
    //  id: 26,
    firstName: "Laetitia",
    lastName: "Menirel",
    startDate: "11/03/2014",
    department: "Engineering",
    dateOfBirth: "08/24/1985",
    street: "High Street",
    city: "Chicago",
    state: "UJ",
    zipCode: "87120",
  },
  {
    // id: 27,
    firstName: "Roman",
    lastName: "Pelio",
    startDate: "01/28/2018",
    department: "Human Resources",
    dateOfBirth: "05/22/1990",
    street: "Sea Street",
    city: "Seattle",
    state: "SG",
    zipCode: "99852",
  },
  {
    // id: 28,
    firstName: "Kristen",
    lastName: "Bird",
    startDate: "09/20/2012",
    department: "Marketing",
    dateOfBirth: "03/15/1975",
    street: "Side Street",
    city: "Boston",
    state: "VL",
    zipCode: "20369",
  },
  {
    // id: 29,
    firstName: "Nico",
    lastName: "Smith",
    startDate: "02/02/2017",
    department: "Legal",
    dateOfBirth: "03/29/1987",
    street: "Round Street",
    city: "Detroit",
    state: "DP",
    zipCode: "36124",
  },
  {
    // id: 30,
    firstName: "Lea",
    lastName: "Regan",
    startDate: "10/08/2015",
    department: "Engineering",
    dateOfBirth: "09/25/1979",
    street: "End Street",
    city: "Baltimore",
    state: "PI",
    zipCode: "79582",
  },
  {
    // id: 31,
    firstName: "Tim",
    lastName: "Legol",
    startDate: "02/13/2021",
    department: "Marketing",
    dateOfBirth: "10/05/1995",
    street: "Holy Street",
    city: "Dallas",
    state: "CM",
    zipCode: "25001",
  },
  {
    // id: 32,
    firstName: "Celia",
    lastName: "Hugh",
    startDate: "04/14/2021",
    department: "Marketing",
    dateOfBirth: "06/14/1992",
    street: "Low Street",
    city: "Austin",
    state: "HY",
    zipCode: "97312",
  },
  {
    // id: 33,
    firstName: "Roman",
    lastName: "Pelio",
    startDate: "01/28/2018",
    department: "Human Resources",
    dateOfBirth: "05/22/1990",
    street: "Sea Street",
    city: "Seattle",
    state: "SG",
    zipCode: "99852",
  },
];

export default dataUser;
